### ISSUE TITLE
multiValued schema attributes throws 'error expected to be a collection in schema extension'

### ISSUE THREAD

**Issue by kanishka3000** [scimmyjs/scimmy#12]
Hi,
This is an awesome library that does exactly what I want. Thank you so much.
I am trying to extend the User resource and add an multiValued property to it. But it seems to throw an error.
**Definition**

```
     const definition = new SCIMMY.Types.SchemaDefinition('Agent', 'urn:ietf:params:scim:schemas:company:Agent', 'Agent', [

            //https://scimmyjs.github.io/SCIMMY.Types.Attribute.html
            new SCIMMY.Types.Attribute('string', 'admin', { required: true, description: 'admin field' }),
            new SCIMMY.Types.Attribute('complex', 'agencies', { required: true, description: 'agencies array field', multiValued: true, direction: 'both' }, [

                new SCIMMY.Types.Attribute('string', 'name', { required: true, description: 'admin field' }),
            ]),
        ]);

        class AgentSchema extends SCIMMY.Types.Schema {
            static get definition() {
                return definition;
            }
        }

        SCIMMY.Resources.declare(SCIMMY.Resources.User.extend(AgentSchema, true))
            .ingress(ingress);
```
**Test**
```
    test('should validate true when Agent has extended attributes', async () => {
        await (new SCIMMY.Resources.User())
            .write({
                'userName': 'someGuy',
                'externalId': '5667',
                'emails': [
                    {
                        value: 'dschrute@example.com',
                        type: 'work',
                        primary: true,
                    },
                ],

                'schemas': ['urn:ietf:params:scim:schemas:company:Agent', 'urn:ietf:params:scim:schemas:core:2.0:User'],
                'urn:ietf:params:scim:schemas:domain:Agent': {
                    admin: 'test-admin',
                    agencies: []
                },
            },
            );
    });
```

This throws following error.
```
SCIMError: Attribute 'agencies' expected to be a collection in schema extension 'urn:ietf:params:scim:schemas:domain:Agent'
```

Test code: https://github.com/kanishka3000/scimmy-learning-tests/blob/42678fe3a871354ab85591b8422805df98f695dd/test/agent.test.ts#L49

**Possible scenario**

It appears that the array is being converted into an object with { 0: 'value', 1: 'value2}. by this function https://github.com/scimmyjs/scimmy/blob/7f05fac4b94dea4ffe073c4be84848524f9ae7d8/src/lib/types/definition.js#L266.

Thanks in advance for assistance.

**Comment by sleelin** [comment]
Hi Kanishka,
Thanks for your feedback!

This is indeed a bug in the way the merge function handles arrays, as you identified.
I have fixed the issue in the release/1.0.0 branch which I am in the process of finalising now.

I would note however that the supplied test case will still throw the following error:
```
SCIMError: Required attribute 'agencies' is missing in schema extension 'urn:ietf:params:scim:schemas:domain:Agent'
```

This is because the 'agencies' attribute is marked as required, but does not contain any actual values.
Let me know if you have any questions about this.

Thanks,
Sam
