### ISSUE TITLE
Usage example for how to return in ingress/egress/degress

### ISSUE THREAD

**Issue by magesh-facilio** [scimmyjs/scimmy#27]
It would be helpful if any example of:
1. how to return an existing user in egress
2. how to return an created user in ingress
3. how to return an deleted user in degress

If I try to someway, it shows 500 error.

**Comment by magesh-facilio** [comment]
Also this is compatible with [Microsoft Entra ID SCIM Validator](https://scimvalidator.microsoft.com/) ?

When I validate the SCIM with this tool, all requests getting failed.

**Comment by sleelin** [comment]
Hi @magesh-facilio,
Examples of what your ingress/egress/degress handlers should look like can be found on the `SCIMMY.Types.Resource` documentation page under the [Type Definitions section](https://scimmyjs.github.io/SCIMMY.Types.Resource.html#typedefs).

Unfortunately, Microsoft's Entra ID SCIM Validator tool does not meet the SCIM RFC specification.
For a detailed explanation of why the tool doesn't meet the specification, and an alternative means of validating your SCIM implementation, see my response in [this issue](https://github.com/scimmyjs/scimmy-routers/issues/10#issuecomment-1947715384) from the scimmy-routers repository.

Let me know if you have any further questions.

Thanks,
Sam
