### ISSUE TITLE
Complex value gives error response if unknown sub-attribute is sent

### ISSUE THREAD

**Issue by christiaangoossens** [scimmyjs/scimmy#41]
If we disable the `name.honorificPrefix` field from the user definition (`SCIMMY.Schemas.User.definition.truncate('name.honorificPrefix')`) and then send data that contains that field, such as:

```json
{
  "addresses": [{
    "country": "Philippines",
    "streetAddress": "870 McLaughlin Turnpike",
    "formatted": "Suite 431 1780 Albert Green, Holliefort, NE 20440-9954",
    "postalCode": "40331",
    "locality": "Tanikaport",
    "primary": true
  }],
  "displayName": "Lavonda Runolfsdottir",
  "nickName": "Sherman Wadd Evver",
  "externalId": "travis.spinka",
  "active": true,
  "userName": "elenafadel",
  "title": "Forward Creative Director",
  "phoneNumbers": [{
    "value": "818-532-0271",
    "primary": true
  }],
  "emails" : [{
    "value": "joya.considine@opensource.suvera.dev",
    "primary": true
  }],
  "password": "garth.yost",
  "schemas": ["urn:ietf:params:scim:schemas:core:2.0:User"],
  "name": {
    "formatted": "Cathrine Gleason",
    "familyName": "Becker",
    "givenName": "Jacklyn",
    "honorificPrefix": "Mrs."
  }
}
```

We will get a 400 error:
```json
{
  "schemas": ["urn:ietf:params:scim:api:messages:2.0:Error"],
  "status": "400", "scimType": "invalidValue",
  "detail": "Complex attribute 'name' does not declare subAttribute 'honorificPrefix'"
}
```

We should instead ignore such fields, just as we do when specifying `SCIMMY.Schemas.User.definition.truncate('phoneNumbers')`, which gives a 200 response for the input above.

I am not sure how to fix this myself, but it likely involves updating https://github.com/scimmyjs/scimmy/blob/8a25458fbc122e27d6b65cf52a91bdd0d140a62d/src/lib/types/attribute.js#L581 and the tests.

**Comment by sleelin** [comment]
Hi @christiaangoossens, apologies for the delay in getting to this.

It's not entirely clear in the spec what the behaviour should be when a client sends a resource containing unknown/undeclared attributes. My initial understanding was that the correct response in this case is the `400 Bad Request` message with `scimType` of `invalidValue` that is currently being returned, however there's actually very little to base this on in the specs. My reasoning for this behaviour was that the client has technically supplied an invalid value for the `name` complex attribute - hence the response. This differs from the behaviour when the client has included a value for an unknown attribute (as opposed to an unknown sub-attribute) on the resource, in which case the value is simply ignored.

Upon closer inspection of [RFC7644](https://datatracker.ietf.org/doc/html/rfc7644) it may actually be more suitable to ignore unknown sub-attributes the same as unknown attributes. I'll make the required changes and include them in the next release.

Thanks,
Sam

**Comment by christiaangoossens** [comment]
@sleelin Thank you for your fixes!

**Comment by sleelin** [comment]
Hi @christiaangoossens, apologies for the delay, version 1.2.4 has now been published to NPM with this fix included.
